certManagerClusterIssuerName: postgres-operator-ca-certificate-cluster-issuer
dockerRegistrySecretName: registry-secret
resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    cpu: 500m
    memory: 300Mi
enableSecurityContext: true